[package]
name = "gxi"
version = "0.2.0"
authors = ["aniketfuryrocks <prajapati.ani306@gmail.com>"]
edition = "2018"
description = "CrossPlatform Native Widget based Component System in rust"
license = "MIT"
repository = "https://github.com/gxi-rs/gxi.git"
homepage = "https://gxi-rs.github.io/"
categories = [
    "gui",
    "wasm",
    "web-programming"
]
keywords = [
    "gxi-rs",
    "wasm",
    "gtk",
    "gui",
    "framework"
]

[workspace]
members = [
    "gxi_macro",
    "examples/desktop",
    "examples/web",
    "tests",
    "gxi-desktop",
    "gxi-web",
]

[dependencies.gxi_macro]
path = "./gxi_macro"
version = "0.2.0"
