[package]
name = "gxi"
version = "0.4.0"
authors = ["aniketfuryrocks <prajapati.ani306@gmail.com>"]
edition = "2018"
description = "Zero-Cost Cross-Platform Native Widget based Component System in Rust"
license = "MIT"
repository = "https://github.com/gxi-rs/gxi.git"
homepage = "https://gxi-rs.com/"
categories = [
    "gui",
    "wasm",
    "web-programming"
]
keywords = [
    "gxi-rs",
    "wasm",
    "gtk",
    "gui",
    "framework"
]

[features]
web = ["gxi-derive/web", "web-sys"]
desktop = ["gxi-derive/desktop"]
default = ["gxi-derive/default"]

[workspace]
members = [
    "gxi-derive",
    "examples/web"
]

[dependencies]
gxi-derive = { path = "gxi-derive", version = "0.1.0", optional = true }
# web
web-sys = { version = "0.3.51", features = ["Element", "Window", "Document", "HtmlElement"], optional = true }
