[package]
name = "gxi"
version = "0.1.3"
authors = ["aniketfuryrocks <prajapati.ani306@gmail.com>"]
edition = "2018"
description = "CrossPlatform Native Widget based Component System in rust"
license = "MIT"
repository = "https://github.com/gxi-rs/gxi.git"
homepage = "https://gxi-rs.github.io/"
categories = [
    "gui",
    "wasm",
    "web-programming"
]
keywords = [
    "gxi-rs",
    "wasm",
    "gtk",
    "gui",
    "framework"
]
resolver = "2"
exclude = [
    "examples"
]

[features]
desktop = ["gxi_desktop_binds"]
web = ["gxi_web_binds"]

[workspace]
members = [
    "gxi_interface",
    "examples/desktop",
    "examples/web",
]

[dependencies]
gxi_interface = { path = "gxi_interface", version = "0" }
#binds
gxi_web_binds = { path = "../gxi_web_binds", optional = true , version = "0" }
gxi_desktop_binds = { path = "../gxi_desktop_binds", optional = true, version = "0" }
