[package]
name = "gxi"
version = "0.1.0"
authors = ["aniketfuryrocks <prajapati.ani306@gmail.com>"]
edition = "2018"
description = "CrossPlatform Native Widget based Component System in rust"
resolver = "2"
exclude = [
    "examples",
    "tests",
]

[features]
desktop = ["gxi_desktop_binds"]
web = ["gxi_web_binds"]

[workspace]
members = [
    "gxi_interface",
    "binds/gxi_web_binds",
    "binds/gxi_desktop_binds",
    "examples/web",
    "examples/cat_fact",
    "macros/update",
    "macros/c",
    "macros/comp",
    "macros/parsers",
    "tests"
]

[dependencies]
gxi_interface = { path = "gxi_interface", version = "" }
#binds
gxi_web_binds = { path = "binds/gxi_web_binds", optional = true , version = "" }
gxi_desktop_binds = { path = "binds/gxi_desktop_binds", optional = true, version = "" }
