[package]
name = "rust_gui"
version = "0.1.0"
authors = ["aniketfuryrocks <prajapati.ani306@gmail.com>"]
edition = "2018"
description = "CrossPlatform Native Widget based Component System in rust"

[dependencies]
gtk = "0.9.2"
c = { path = "macros/c" }
x = { path = "macros/x" }
