[package]
name = "rust_gui"
version = "0.1.0"
authors = ["aniketfuryrocks <prajapati.ani306@gmail.com>"]
edition = "2018"
description = "CrossPlatform Native Widget based Component System in rust"
resolver = "2"

[features]
desktop = ["desktop_binds"]
web = ["web_binds"]

[workspace]
members = [
    "rust_gui_interface",
    "binds/web_binds",
    "binds/desktop_binds",
    "examples/web",
    "examples/cat_fact",
    "macros/update",
    "macros/c",
    "macros/comp",
    "macros/parsers"
]

[dependencies]
rust_gui_interface = { path = "rust_gui_interface" }
#binds
web_binds = { path = "binds/web_binds", optional = true }
desktop_binds = { path = "binds/desktop_binds", optional = true }
