[package]
name = "rust_gui"
version = "0.1.0"
authors = ["aniketfuryrocks <prajapati.ani306@gmail.com>"]
edition = "2018"
description = "CrossPlatform Native Widget based Component System in rust"

[workspace]
members = [
    "examples/cat_fact",
    "macros/update",
    "macros/c",
    "macros/comp",
    "macros/parsers",
]

[dependencies]
gtk = "0.9.2"
c = { path = "macros/c" }
comp = { path = "macros/comp" }
parsers = { path = "macros/parsers" }
update = { path = "macros/update" }
tokio = { version = "", features = ["full"] }
glib = "0.10.3"
