[package]
name = "parsers"
version = "0.1.0"
authors = ["aniketfuryrocks <prajapati.ani306@gmail.com>"]
edition = "2018"

[features]
web = []
desktop = []

[dependencies]
syn = { version = "", features = ["full"] }
quote = "1.0.9"