[package]
name = "example"
version = "0.1.0"
edition = "2018"

[dependencies]
gxi = { version = "^0.6.0", path = "../../", features = ["web", "async-web"] }
console_error_panic_hook = "0.1.7"
wasm-bindgen-futures = "0.4.31"
reqwest = "0.11.11"
