[package]
name = "web"
version = "0.1.4"
authors = ["aniketfuryrocks <prajapati.ani306@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.64"
reqwest = "0.11.3"

[dependencies.gxi]
path = "../../"
features = ["web"]
version = ""
