[package]
name = "x"
version = "0.1.0"
authors = ["aniketfuryrocks <prajapati.ani306@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "", features = ["full"] }
parsers = { path = "../parsers" }
quote = "1.0.9"