name: Cross Platform Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu-tests-and-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run gtk-3 deps install
        run: |
            sudo apt-get install libgtk-3-dev

      - name: Run desktop build
        run: |
          cd examples/desktop
          cargo build

  windows-tests-and-builds:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-rust

      - name: Run desktop build
        run: |
          cd examples/desktop
          cargo build