name: Rust

on:
  push:
    branches: [ main, ci-test ]
  pull_request:
    branches: [ main, ci-test ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Macro tests
        run: |
          cargo test

  desktop-ubuntu-example-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Ubuntu Desktop Build
        run: |
          sudo apt install libgtk2.0-dev
          cd examples/desktop
          cargo build

  desktop-windows-example-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-rust
      - name: cd
        run: |
          cd examples/desktop
          cargo build