name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Desktop
      working-directory: examples/cat_fact
      run: cargo build --verbose
    - name: Build Web
      working-directory: examples/web
      run: cargo build --verbose
