name: Rust

on:
  push:
    branches: [ main, nightly ]
  pull_request:
    branches: [ main, nightly ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
