name: Tests

on:
  push:
    branches: [main, nightly]
  pull_request:
    branches: [main, nightly]

env:
  CARGO_TERM_COLOR: always

jobs:
  macro-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo target
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - name: Run linter
        run: |
          cargo clippy

      - name: Run Macro tests
        run: |
          cargo test --workspace --lib
