name: Tests

on:
  push:
    branches: [main, nightly]
  pull_request:
    branches: [main, nightly]

env:
  CARGO_TERM_COLOR: always

jobs:
  macro-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: rustup component add clippy

      - name: Run linter
        run: |
          cargo clippy

      - name: Run Macro tests
        run: |
          make test
