name: Build

on:
  push:
    branches: [ main, nightly ]
  pull_request:
    branches: [ main, nightly ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run linter
        run: |
          cargo clippy

      - name: Run Macro tests
        run: |
          cargo test
